Default values pulled out to own file.
lafriks/go-tiled pull request #43
Opened 2020-12-05 18:13 UTC by Qwarkster

2020-12-05 18:14 UTC, Qwarkster commented
Still some review of default values to be setting, but the concept of getting defaults all set in the same file has been achieved.

2021-03-27 21:06 UTC, lafriks requested changes

2021-03-27 21:06 UTC, lafriks commented on tmx_map.go
> +	item.baseDir = m.baseDir
```suggestion
	item := aliasMap{
		loader:      m.loader,
		baseDir:     m.baseDir,
	}
```

2021-03-27 21:07 UTC, lafriks commented
sorry for long review, can you please fix this

2021-03-29 14:30 UTC, lafriks requested changes

2021-03-29 14:34 UTC, lafriks approved these changes

2021-03-29 14:35 UTC, merged