Export Tileset.BaseDir to support manually loaded TSX files / Tilesets
lafriks/go-tiled pull request #67
Opened 2022-08-13 18:21 UTC by jabolopes

Hi,

I wanted to ask if it would be possible to export the Tileset.BaseDir field?

Context: It's possible to load TSX files directly using the xml.NewDecoder() but it's not
possible to set the Tileset.baseDir field since this field is not exported.

This means that for TSX files loaded via the xml.NewDecoder(), it's not possible
to use the Tileset.GetFileFullPath() method to determine the location of
resources relative to the path of the tileset, e.g., the tileset image.

So far I have been employing a workaround which is to always pass the Tileset
and also the baseDir together as separate arguments, which is cumbersome. It
would be ideal if it were possible to set the Tileset.BaseDir field
directly. This means that if a TMX map is loaded by the go-tiled library, then
the go-tiled library sets the Tileset.BaseDir. However, if the TSX tileset is
loaded manually, then the code loading it manually can also set the field.

An alternative would be to extend the go-tiled library with functions to load
the Tileset from a file, from a reader, etc, but this would be additional
effort.

At the same time, the Tileset already contains a field (Tileset.SourceLoaded)
which is exported and annotated with `xml:"-"` so this approach of exported
fields that are not serialized is not new.

This patch exports the Tileset.BaseDir field. Other ideas are welcome!

2022-08-13 20:57 UTC, lafriks commented
As baseDir is more of an internal variable I would probably prefer it to stay that way. I think it would be better to add SetBaseDir function to set it and BaseDir function to access if needed

2022-08-14 08:46 UTC, jabolopes commented
Thank you for the quick response! Sounds good. I updated the patch to define a getter / setter for Tileset.baseDir as suggested.

2022-08-14 10:07 UTC, lafriks requested changes

2022-08-14 10:07 UTC, lafriks commented on tmx_tileset.go
> +func (ts *Tileset) BaseDir() string { return ts.baseDir }
```suggestion
func (ts *Tileset) BaseDir() string {
	return ts.baseDir
}
```

2022-08-14 10:07 UTC, lafriks commented on tmx_tileset.go
> +func (ts *Tileset) SetBaseDir(baseDir string) { ts.baseDir = baseDir }
```suggestion
func (ts *Tileset) SetBaseDir(baseDir string) {
	ts.baseDir = baseDir
}
```

2022-08-14 10:26 UTC, lafriks approved these changes

2022-08-14 10:27 UTC, merged

2022-08-14 10:27 UTC, lafriks commented
Thank you for PR